name: Deploy code to Heroku

on:
  push:
    branches:
      - master
    paths:
      - "src/*"
      - ".github/workflows/Deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - name : add git username
        run: git config --global user.name 'Sarikalikhar11'
      - name : add git email
        run: git config --global user.email 'sarikalikhar2619@gmail.com'
      - name : add heroku remote
        run: git remote add heroku https://heroku:d1b10d6f-9baf-4b51-8b0b-5984d362b8f8@git.heroku.com/server-ecomm.git
      - name: fetch the repo
        run: git fetch --unshallow      d1b10d6f-9baf-4b51-8b0b-5984d362b8f8
      - name: push to heroku
        run: git push heroku master --force