name: Deploy code to Heroku

on:
  push:
    branches:
      - master
    paths:
      - "src/*"
      - ".github/workflows/Deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - name : add git username
        run: git config --global user.name 'kartik18g'
      - name : add git email
        run: git config --global user.email 'gupta.kartik18kg@gmail.com'
      - name : add heroku remote
        run: git remote add heroku https://heroku:8f02f5f0-2d3b-4a74-91c6-34e327b72808@git.heroku.com/devtown-tshirt-backend.git
      - name: fetch the repo
        run: git fetch --unshallow
      - name: push to heroku
        run: git push heroku master --force